name: ArgoCD

on:
  workflow_dispatch:

jobs:
  deploy_argocd:
    runs-on: self-hosted
    steps:
      - name: Install kubectl
        run: |
          sudo apt-get update && sudo apt-get install -y apt-transport-https gnupg
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update
          sudo apt-get install -y kubectl

      - name: Create namespace argocd
        run: kubectl create namespace argocd || [ $? -eq 1 ]

      - name: Apply ArgoCD manifests
        run: kubectl patch svc argocd-server -n argocd -p '{"spec":{"type":"LoadBalancer"}}'

      - name: Patch ArgoCD service type
        run: kubectl patch svc argocd-server -n argocd --type='json' -p='[{"op":"replace","path":"/spec/type","value":"LoadBalancer"}]'

      - name: Retrieve ArgoCD admin password
        run: |
          ARGOCD_PASSWORD=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)
          echo "ArgoCD initial admin password: $ARGOCD_PASSWORD"
