name: CI

on:
  workflow_dispatch:

jobs:
  destroy_eks_cluster:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Destroy EKS cluster
        run: terraform destroy -auto-approve
