name: CI

on:
  workflow_dispatch:

jobs:
  destroy_eks_cluster:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialize Terraform
        run: terraform init

      - name: Select Terraform workspace
        run: terraform workspace select ben-eks-project-5i3eUe3C

      - name: Plan destruction
        run: terraform plan -destroy

      - name: Destroy EKS cluster
        run: terraform destroy -auto-approve
